apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJVRkl3U2pORFZERXlPbWRvY0Y5cVpVTXhUbGQwYWs1c1dVWlZlWHByU1RoWlVrSTFiVGhFUjFwWFluUXpRa0ZYYzJrPSINCiAgICB9DQogIH0NCn0=
type: kubernetes.io/dockerconfigjson
