apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-container
        image: ghcr.io/PR0J3CT12/cinemaabyss-proxy-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: cinemaabyss-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000