{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: proxy-container
          image: "{{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}"
          imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.proxyService.service.targetPort }}
          env:
            - name: MOVIES_MIGRATION_PERCENT
              value: {{ .Values.config.moviesMigrationPercent | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: {{ .Values.proxyService.service.port }}
      targetPort: {{ .Values.proxyService.service.targetPort }}
{{- end }}